apiVersion: horizon.openstack.org/v1beta1
kind: Horizon
metadata:
  name: horizon
spec:
  replicas: 1
  secret: "osp-secret"
  containerImage: quay.io/podified-antelope-centos9/openstack-horizon:current-podified
  customServiceConfig: |
    SESSION_TIMEOUT = 3600
